mpi:
  - nompi
  - openmpi  # [not win]
  - mpich  # [not win]

pin_run_as_build:
  openmpi:
    max_pin: x.x

pin_run_as_build:
  mpich:
    max_pin: x.x

channel_sources:
  - ramonaoptics,conda-forge
channel_targets:
  - ramonaoptics main

